name: 🚀 Coleta PSI

on:
  schedule:
    - cron: '0 3 * * *'    # todo dia às 03:00 UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PSI_KEY: ${{ secrets.PSI_KEY }}
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install deps
        run: npm ci

      - name: Coletar dados PSI
        timeout-minutes: 10
        env:
          PSI_CONCURRENCY: 100
          PSI_MAX_RETRIES: 2
          PSI_RETRY_DELAY_MS: 1000

          PSI_REQUESTS_PER_MIN: 60

        run: node collect-psi.js

      - name: Handle PSI Collection Errors
        if: always()
        run: |
          if [ -f psi_errors.log ] && [ -s psi_errors.log ]; then
            echo "PSI collection errors found. Preparing TODO.md."
            echo "HAS_PSI_ERRORS=true" >> $GITHUB_ENV
          else
            echo "No PSI collection errors found."
            echo "HAS_PSI_ERRORS=false" >> $GITHUB_ENV
          fi

      - name: Archive PSI Error Log
        if: env.HAS_PSI_ERRORS == 'true'
        run: |
          mkdir -p data/psi_error_reports
          cp psi_errors.log data/psi_error_reports/psi_errors_${{ github.run_id }}.log
          echo "PSI error log archived to data/psi_error_reports/psi_errors_${{ github.run_id }}.log"

      - name: Create/Update TODO.md if errors exist
        if: env.HAS_PSI_ERRORS == 'true'
        run: |
          echo "## PSI Collection Error Reports (P0)" > TODO.md
          echo "" >> TODO.md
          echo "Errors may have been detected during scheduled PSI data collections." >> TODO.md
          echo "Please check the \`data/psi_error_reports/\` directory for log files named \`psi_errors_<run_id>.log\`." >> TODO.md
          echo "Review these logs and address any reported issues." >> TODO.md
          echo "" >> TODO.md
          echo "Workflow run that last updated this TODO: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}" >> TODO.md

      - name: Commit and Push Error Reports and TODO.md to Main Branch
        if: env.HAS_PSI_ERRORS == 'true'
        run: |
          ORIGINAL_BRANCH="${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}"
          echo "Committing error reports to branch: $ORIGINAL_BRANCH"

          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # Ensure we are on the correct branch and it's up-to-date
          git checkout $ORIGINAL_BRANCH
          git pull origin $ORIGINAL_BRANCH

          # Added data/psi_processing_state.json from fix/psi-commit-error
          git add TODO.md data/psi_error_reports/ data/psi_processing_state.json

          if ! git diff --staged --quiet; then
            # Updated commit message from fix/psi-commit-error
            git commit -m "docs: Log PSI collection errors, update TODO, and save state

            Errors were detected during the scheduled PSI data collection.
            Details have been archived to data/psi_error_reports/
            TODO.md has been updated, and the latest processing state
            has been saved to data/psi_processing_state.json.

            Workflow run: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
            git push origin $ORIGINAL_BRANCH
          else
            # Updated message from fix/psi-commit-error
            echo "No changes to TODO.md, error reports, or processing state to commit."
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit e push dos resultados
        run: |
          if [ -f "data/psi-results.json" ]; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            # Added data/psi_processing_state.json from fix/psi-commit-error
            git add data/psi-results.json data/psi-results.csv data/psi_processing_state.json
            # Only commit if there are changes
            if ! git diff --staged --quiet; then
              # Updated commit message from fix/psi-commit-error
              git commit -m "chore: atualiza PSI data e estado de processamento"
              git push
            else
              # Updated message from fix/psi-commit-error
              echo "No changes to PSI data or processing state to commit."
            fi
          else
            # Updated message from fix/psi-commit-error
            echo "data/psi-results.json not found. Skipping commit of results and state."
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Cleanup temporary error log
        if: always()
        run: rm -f psi_errors.log
